name: Generate Rules
on:
  workflow_dispatch:
  schedule:
    - cron: "1 3 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "COMMIT_INFO=$(TZ='Asia/Hongkong' date +%F\ %H:%M:%S)" >> $GITHUB_ENV
          echo "cn_cidr=${{ secrets.SOURCE_CN_IPV4 }}" >> $GITHUB_ENV
          echo "cn_cidr6=${{ secrets.SOURCE_CN_IPV6 }}" >> $GITHUB_ENV
        shell: bash

      - uses: actions/checkout@v4.1.3

      - name: Generate cn.list file
        run: |
          curl -sSL ${cn_cidr} | grep -v '#' | sed 's/^/IP-CIDR,/' > cn.list
          curl -sSL ${cn_cidr6} | grep -v '#' | sed 's/^/IP-CIDR6,/' >> cn.list

      - name: Move files to publish directory
        run: |
          git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" publish
          mv ./*.list publish/

      - name: Git push assets
        run: |
          cd publish || exit 1
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if [[ -n $(git status --porcelain) ]]; then
              git commit -m "${{ env.COMMIT_INFO }}"
              git push
          fi

      - name: Cleanup Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2
